; Script generated by Gemini CLI
; For use with Inno Setup Compiler
;
; This script is a basic template. You may need to customize it
; further based on your game's specific needs (e.g., custom icons,
; uninstallation behavior, registry entries, etc.).

[Setup]
AppName=Space Shooter
AppVersion=1.0
AppPublisher=Erick de Oliveira Bessa Xavier
DefaultDirName={autopf}\Space Shooter
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\Space_Shooter.exe
OutputDir=Output
OutputBaseFilename=setup_spaceshooter
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Files]
Source: "dist\Space_Shooter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "game\assets\*"; DestDir: "{app}\game\assets"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\Space Shooter"; Filename: "{app}\Space_Shooter.exe"
Name: "{autodesktop}\Space Shooter"; Filename: "{app}\Space_Shooter.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Space_Shooter.exe"; Description: "{cm:LaunchProgram,Space Shooter}"; Flags: shellexec postinstall skipifdoesntexist

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
