; Script generated by Gemini CLI
; For use with Inno Setup Compiler
;
; This script is a basic template. You may need to customize it
; further based on your game's specific needs (e.g., custom icons,
; uninstallation behavior, registry entries, etc.).

[Setup]
AppName=Jogo de Nave Espacial
AppVersion=1.0
AppPublisher=Erick de Oliveira Bessa Xavier
DefaultDirName={autopf}\Jogo de Nave Espacial
DisableProgramGroupPage=yes
UninstallDisplayIcon={app}\Jogo_Nave.exe
OutputDir=Output
OutputBaseFilename=setup_jogo_nave
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Files]
Source: "dist\Jogo_Nave.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "game\assets\*"; DestDir: "{app}\game\assets"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\Jogo de Nave Espacial"; Filename: "{app}\Jogo_Nave.exe"
Name: "{autodesktop}\Jogo de Nave Espacial"; Filename: "{app}\Jogo_Nave.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Jogo_Nave.exe"; Description: "{cm:LaunchProgram,Jogo de Nave Espacial}"; Flags: shellexec postinstall skipifdoesntexist

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
