# game/core/render_config.py


class RenderConfig:
    # Celestial Manager configurations
    CELESTIAL_NUM_BODIES = 2
    CELESTIAL_SCALE_MIN = 0.1
    CELESTIAL_SCALE_MAX = 0.3
    CELESTIAL_ALPHA_MIN = 50
    CELESTIAL_ALPHA_MAX = 200
    CELESTIAL_SPEED_BASE_MIN = 50
    CELESTIAL_SPEED_BASE_MAX = 150
    CELESTIAL_SPEED_OFFSET = 20
    CELESTIAL_RESET_Y_MIN_MULTIPLIER = -1.5
    CELESTIAL_RESET_Y_MAX_MULTIPLIER = -0.5
    CELESTIAL_MIN_GAP = 50  # Minimum horizontal gap between celestial bodies

    # Starfield configurations
    STARFIELD_NUM_STARS = 30
    STARFIELD_SPEED_MIN = 30
    STARFIELD_SPEED_MAX = 150
    STARFIELD_BRIGHTNESS_MIN = 100
    STARFIELD_BRIGHTNESS_MAX = 255
